### PR TITLE
Update company backend

### PR DESCRIPTION
**Pull request by marsam**
Hi:
I've added the missing commands to the backend.

Thanks in advance.

### CODE REVIEW

**Comment by syohex** [comment]
Thanks for great changes.

I suppose it is hard to see annotation characters. How about inserting space(or some character) before annotation ?

**Comment by marsam** [comment]
I really don't think it's necessary; but do you have a format in mind?

**Comment by syohex** [comment]
company-jedi

In this case, candidates are `getrecursionlimit` and `getrefcount`, and both of annotations are `f`. 
But they looks like `getrecursionlimitf` and `getrefcountf`.

I suppose it is better to inserting space or wrap some characters as bellow.

company-jedi2

company-jedi3

How about you ?

**Comment by marsam** [comment]
Hi, I've added wrapping brackets in annotations.
btw, I was wondering why your completions looks _weird_, and was because I forgot that I have `(setq company-tooltip-align-annotations t)` in my init.el.

**Comment by syohex** [comment]
@marsam Thanks great stuff!! :+1:

**Comment by stardiviner** [comment]
@syohex What popup are you using? popup.el? how to add that black color border?

**Comment by syohex** [comment]
It is [company-quickhelp](https://github.com/expez/company-quickhelp) which uses `pos-tip`.

**Pull request merged**
